Sat sprint1 06 march
bcgov/MoH-SAT pull request #836
Opened 2023-03-13 17:30 UTC by deepakmulamalla

Development Related to ESA-1472 User story

2023-03-13 20:29 UTC, cgiSunilM requested changes

2023-03-14 13:19 UTC, deepakmulamalla commented on force-app/main/default/objects/Contact/fields/ESA_Provider_Specialty__c.field-meta.xml
> +    <externalId>false</externalId>
Changes are done as per comments.

2023-03-14 13:19 UTC, deepakmulamalla commented on force-app/main/default/classes/ESA_cls_accountTriggerHandler.cls
> +        set<id> accountIdSet = new set<id>();
Changes are done as per comments.

2023-03-14 13:20 UTC, deepakmulamalla commented on force-app/main/default/objects/Contact/fields/Provider_Specialty__c.field-meta.xml
> +    <visibleLines>10</visibleLines>
Yes this is the business requirement to display 10 lines.

2023-03-14 13:20 UTC, deepakmulamalla commented on force-app/main/default/classes/ESA_cls_accountTriggerHandler.cls
> +            Boolean isSpecialtyChanged = trigger.isUpdate && oldAccountMap.get(accObj.id).Provider_Specialty__pc != newAccountMap.get(accObj.id).Provider_Specialty__pc;
In case of update, Stamping should be done only if provider specialty field is changed and in trigger it is not checked.

2023-03-14 14:18 UTC, avikghoshMOH approved these changes

2023-03-14 16:29 UTC, rg90ac approved these changes

2023-03-14 17:00 UTC, merged