Updates to team leads permission
bcgov/MoH-SAT pull request #904
Opened 2023-08-01 22:16 UTC by vasanthid23

2023-08-01 22:54 UTC, cgijeffolsen requested changes
@vasanthid23 At this time we want to review the intent of the validation rules with the business so please hold off on committing this item till we hear back. I expect the rule logic to be changed before the next deployment.
Thank you, Jeff

2023-08-02 17:14 UTC, deepakmulamalla approved these changes

2023-08-02 18:06 UTC, vasanthid23 commented
@cgijeffolsen I have updated the PR to remove the updates to account name validation rule as we no longer needed it . 
Can i include  the changes to make validation rule inactive in the repo as well to be sync in production ? 


Thanks,
Vasanthi

2023-08-02 18:11 UTC, merged

2023-08-02 18:17 UTC, cgijeffolsen commented
Yes that would be the safest thing to do for the time being.

Thank you!

Jeff Olsen
CGI | Senior Consultant | cell: 604.761.9992

From: vasanthid23 ***@***.***>
Sent: Wednesday, August 2, 2023 11:06 AM
To: bcgov/MoH-SAT ***@***.***>
Cc: Olsen, Jeffrey ***@***.***>; Mention ***@***.***>
Subject: Re: [bcgov/MoH-SAT] Updates to team leads permission (PR #904)

EXTERNAL SENDER: Do not click any links or open any attachments unless you trust the sender and know the content is safe.
EXPÉDITEUR EXTERNE: Ne cliquez sur aucun lien et n’ouvrez aucune pièce jointe à moins qu’ils ne proviennent d’un expéditeur fiable, ou que vous ayez l'assurance que le contenu provient d'une source sûre.



@cgijeffolsen<https://urldefense.com/v3/__https:/github.com/cgijeffolsen__;!!AaIhyw!vtKG--fPW6dvs2Bl0mwKOi25eTW1n61_HXsWRZlHJxWau95qrBpUv6A5albaBiVf1ahBQDRX-B08tH8BGFVlLdOe$> I have updated the PR to remove the updates to account name validation rule as we no longer needed it .
Can i include the changes to make validation rule inactive in the repo as well to be sync in production ?

Thanks,
Vasanthi

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/bcgov/MoH-SAT/pull/904*issuecomment-1662710767__;Iw!!AaIhyw!vtKG--fPW6dvs2Bl0mwKOi25eTW1n61_HXsWRZlHJxWau95qrBpUv6A5albaBiVf1ahBQDRX-B08tH8BGIrljcb3$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AWWXA5ZMTZHK7Y5CWS6VLOLXTKJJJANCNFSM6AAAAAA3AMSGF4__;!!AaIhyw!vtKG--fPW6dvs2Bl0mwKOi25eTW1n61_HXsWRZlHJxWau95qrBpUv6A5albaBiVf1ahBQDRX-B08tH8BGEh9CY0D$>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>